"""batch 2: auth

Revision ID: 6d6ef50b96c6
Revises: 9c4c3aed2b82
Create Date: 2026-09-23 15:55:07.805925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6ef50b96c6'
down_revision = '9c4c3aed2b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_shift_setting_id'), ['shift_setting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_zone_id'))
        batch_op.drop_index(batch_op.f('ix_users_shift_setting_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
